config/routes.rb
Rails.application.routes.draw do
 
  namespace :api do
    post 'users/sign_in', controller: 'users#sign_in'
    delete 'users/sign_out', controller: 'users#sign_out'
    resources :tags, only: :index
    resources :tags_infos, only: :index
  end

  resources :payments

  devise_for :users, :path_prefix => 'authentication'

  resources :users, param: :encoded_id

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get 'upload/tags_info'

  resources 'site-requests', :controller => :site_requests, :as => :site_requests

  resources :publishers, path: 'publisher/signup' do
    collection do
      get 'thank-you'
    end
  end

  resources :pages do
    post :search_index, :on => :collection
  end

  resources :tags, param: :encoded_id do
    collection do
      get ':encoded_id/export', to: 'tags#export', as: :export
    end
  end

  resources :tags_infos

  resources :uploads do
    collection { post :import }
  end

  resources :reports do
    get :download_csv, on: :collection
  end

  resources :sites do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'ads_txt/download', to: 'ads_txt#download', controller: 'ads_txt'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_many :tags_infos, dependent: :destroy

  before_validation :generate_hex, :on => :create
  validates :user_id, presence: true
  validates :name, presence: true, length: {minimum: 3, maximum: 50}

  validates :file,
            attachment_content_type: {content_type: %w(text/plain text/html application/pdf application/xls application/xlsx application/doc application/docx application/vnd.ms-excel application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document), message: ' Only PDF, EXCEL, WORD or TEXT files are allowed.'
            },
            attachment_size: {less_than: 5.megabytes, :message => ' File must be less than 5 megabytes in size '}

  has_attached_file :file

  def generate_hex
    loop do
      self.encoded_id = SecureRandom.hex
      break unless self.class.exists?(encoded_id: encoded_id)
    end
  end


  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |result|
        csv << result.attributes.values_at(*column_names)
      end
    end
  end
  
 
  def self.search(search)
    if search.present?
      where(' LOWER(name) LIKE ? ', "%#{search.downcase}%")
    else
      all
    end
  end
end

app/controllers/api/tags_controller.rb
module Api
  class TagsController < ApplicationController
    before_action :authenticated_user!
    include ApplicationHelper

    include Swagger::Docs::ImpotentMethods
    respond_to :json
    swagger_controller :users, 'Tags'

    swagger_api :index do |api|
      summary "List user's tags"
      ApplicationController.add_auth_params(api)
      ApplicationController.add_response_params(api)
      response HTTP_STATUS_CODE_808, 'Invalid Password'
    end
    def index
      @data = Tag.where(user_id: @current_user.id)
      data = ActiveModel::ArraySerializer.new(@data, each_serializer: TagSerializer)
      send_response(HTTP_STATUS_CODE_200, true, I18n.t('index'), data)
    rescue => e
      send_response(HTTP_STATUS_CODE_500, false, e.message)
    end
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :authenticate_user!
  include ApplicationHelper

  def index
    if current_user.has_role? :admin
      @tags = Tag.joins(:user).search(params[:search]).order('is_active DESC').page(params[:page]).per(10)
      add_breadcrumb 'Add Website', new_tag_path
    else
      @tags = Tag.joins(:user).search(params[:search]).where(:user_id => current_user.id).order(name: :asc).page(params[:page]).per(10)
      add_breadcrumb 'home', :root_path
      add_breadcrumb 'Websites', :tags_path
    end
  end

  def show
    if current_user.has_role? :customer
      tags = Tag.joins(:user).find_by(:encoded_id => params[:encoded_id])

      @tags_breadcrumb = tags

      add_breadcrumb 'home', :root_path
      add_breadcrumb 'Websites', :tags_path
      add_breadcrumb "#{@tags_breadcrumb.name}", :tag_path

      # Add Rows and Values
      data_table = GoogleVisualr::DataTable.new

      data_table.new_column('date', 'Date')
      data_table.new_column('number', 'Impressions')
      data_table.new_column('number', 'Earnings')

      @tags_infos = TagsInfo.where(:tag_id => tags.id).includes(:tag => :tags_infos).order(frm_date: :desc).page(params[:page]).per(10)

      @tags_infos.each do |tag_info|
        data_table.add_rows([[tag_info.frm_date, tag_info.ad_request, tag_info.partner_revenue]])
      end

      opts = {:width => 750, :height => 354, animation: {startup: true, duration: 1000, easing: 'out'}, :title => 'Total Ad Revenue', :curveType => 'function', hAxis: {title: 'Date', titleTextStyle: {color: '#000000'}}, series: {0 => {targetAxisIndex: 0}, 1 => {targetAxisIndex: 1}}, vAxes: {0 => {title: 'Impressions'}, 1 => {title: 'dollars', format: '$#,###'}}}

      @chart = GoogleVisualr::Interactive::LineChart.new(data_table, opts)
    else
      @tag = Tag.find_by(:encoded_id => params[:encoded_id])
      @tags_infos = TagsInfo.where(:tag_id => @tag.id).order(frm_date: :desc).page(params[:page]).per(10)
    end


  end

  def export

    tags = Tag.joins(:user).find_by(:encoded_id => params[:encoded_id])

    @tags_infos = TagsInfo.where(:tag_id => tags.id).includes(:tag => :tags_infos).order(frm_date: :desc)
    respond_to do |format|
      format.html
      format.csv { send_data @tags_infos.to_csv, filename: "Report-#{tags.name}-#{Date.today}.csv" }
    end

  end

  def new
    @tag = Tag.new
  end

  def create
    begin
      Tag.create!(tag_params.merge(created_by: current_user.id))
      flash[:notice] = "Tag successfully created."
      redirect_to tags_path
    rescue => err # rescues all exceptions
      logger.error(err.to_s)
      flash[:error] = err.to_s
      redirect_to new_tag_path
    end
  end

  def edit
    @tag = Tag.find_by(:encoded_id => params[:encoded_id])
  end

  def update
    @tag = Tag.find_by(:encoded_id => params[:encoded_id])
    if update_tag
      flash[:notice] = "Tag successfully updated."
      redirect_to tags_path
    else
      flash[:error] = @tag.errors
      redirect_to edit_tag_path
    end
  end

  def destroy
    @tag = Tag.find_by(:encoded_id => params[:encoded_id])
    @tag.destroy
    flash[:success] = "Record deleted succesfully"
    redirect_to tags_path
  end

  private

  def update_tag
    @tag = Tag.find(params[:encoded_id])

    param = params[:tag][:is_active]

    if param.present?
      if param == '1'
        value = true
      else
        value = false
      end
      form_params = {:is_active => value}

    else
      form_params = tag_params
    end


    return @tag.update!(form_params.merge(updated_by: current_user.id))
  end

  def tag_params
    params.require(:tag).permit(:name, :user_id, :is_active, :file, :created_by, :updated_by)
  end

end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/show/_admin.html.erb
<div class="content bg-gray-lighter padding-header">
  <div class="row">
    <div class="col-sm-4">
      <h1 class="page-heading ">
        <%= @tag.name.titleize %>
      </h1>
    </div>
    <div class="col-sm-8 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Websites', tags_path %></li>
        <li>
            <% if @tag.is_active %>
                <%= link_to 'Add Information', new_tags_info_path(:tag_id => @tag.encoded_id)%>
            <% else %>
                Add Information
            <% end %>
        </li>
      </ol>
    </div>
  </div>
</div>

<div class="content">
  <div class="block">
    <div class="block-content">
      <table class="table table-striped table-borderless table-header-bg">
        <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">Total Impressions</th>
          <th class="text-center">Paid Impressions</th>
          <th class="text-center">eCPM</th>
          <th class="text-center">Fill Rate</th>
          <th class="text-center">Partner Revenue</th>
          <th class="text-center">Date</th>
          <th class="text-center">Action</th>
        </tr>
        </thead>
        <tbody>
        <% if @tags_infos.present? %>
            <% counter = (@tags_infos.current_page - 1) * 10  %>
            <% @tags_infos.each_with_index do |taginfo, i| %>
                <tr>
                  <td class="text-center"><%= counter + i + 1  %></td>
                  <td class="text-center"><%= number_with_delimiter(taginfo.ad_request.to_i, delimiter: ',') %></td>
                  <td class="text-center"><%= number_with_delimiter(taginfo.match_request.to_i, delimiter: ',') %></td>
                  <td class="text-center"><%= number_to_currency_dollar(taginfo.ecpm) %></td>
                  <td class="text-center"><%= number_to_percentage_fill(taginfo.fill_rate) %></td>
                  <td class="text-center"><%= number_to_currency_dollar(taginfo.partner_revenue) %></td>
                  <td class="text-center"><%= taginfo.frm_date.strftime('%d-%m-%Y') %></td>
                  <td class="text-center">
                    <% if @tag.is_active %>
                        <%= link_to 'Edit', edit_tags_info_path(taginfo.id) %>
                        <%= link_to 'Delete',  taginfo,  method: :delete, data: { confirm: 'Are you sure?' } %>
                    <% else %>
                        Edit Delete
                    <% end %>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td colspan="6" class="text-center">Nothing to show.</td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-sm-6">

        <%= link_to '<i class="fa fa-file-excel-o"></i> Export'.html_safe, export_tags_path(format: 'csv'), :class => 'btn btn-primary push-5-r push-10', :style => 'margin-top: 22px;margin-left: 20px;' %>
      </div>
      <div class="col-sm-4">
        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_1_paginate">
          <%= paginate @tags_infos %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tags/show/_customer.html.erb
<div class='content bg-gray-lighter'>
  <div class='row items-push'>
    <div class='col-sm-7'>
      <h1 class='page-heading'>
        <%= @tags_breadcrumb.name %>
      </h1>
    </div>
    <div class='col-sm-5 text-right hidden-xs'>
      <ol class='breadcrumb push-10-t'>
        <%= render_breadcrumbs :tag => :li, :separator => "" %>
      </ol>
    </div>
  </div>
</div>

<div class='content'>
  <div class='row'>
    <div class='col-lg-9'>
      <div class='block'>
        <div class='block-header'><h3 class='block-title'>Daily Report</h3></div>
        <div class='block-content block-content-full bg-gray-lighter text-center'>
          <div id='chart'>
            <div class='sk-circle'>
              <div class='sk-circle1 sk-child'></div>
              <div class='sk-circle2 sk-child'></div>
              <div class='sk-circle3 sk-child'></div>
              <div class='sk-circle4 sk-child'></div>
              <div class='sk-circle5 sk-child'></div>
              <div class='sk-circle6 sk-child'></div>
              <div class='sk-circle7 sk-child'></div>
              <div class='sk-circle8 sk-child'></div>
              <div class='sk-circle9 sk-child'></div>
              <div class='sk-circle10 sk-child'></div>
              <div class='sk-circle11 sk-child'></div>
              <div class='sk-circle12 sk-child'></div>
            </div>
            <%= render_chart @chart, 'chart' %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="content">
  <div class="block">
    <div class="block-content">
      <table class="table table-responsive table-header-bg">
        <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">Tag Name</th>
          <th class="text-center">Total Impressions</th>
          <th class="text-center">Paid Impressions</th>
          <th class="text-center">eCPM</th>
          <th class="text-center">Fill Rate</th>
          <th class="text-center">Partner Revenue</th>
          <th class="text-center">Date</th>
        </tr>
        </thead>
        <tbody>
        <% if @tags_infos.present? %>
            <% counter = (@tags_infos.current_page - 1) * 10  %>
            <% @tags_infos.each_with_index do |taginfo, i| %>
                <tr>
                  <td class="text-center"><%= counter + i + 1  %></td>
                  <td class="text-center"><%= taginfo.tag.name %></td>
                  <td class="text-center"><%= number_with_delimiter(taginfo.ad_request.to_i, delimiter: ',') %></td>
                  <td class="text-center"><%= number_with_delimiter(taginfo.match_request.to_i, delimiter: ',') %></td>
                  <td class="text-center"><%= number_to_currency_dollar(taginfo.ecpm) %></td>
                  <td class="text-center"><%= number_to_percentage_fill(taginfo.fill_rate) %></td>
                  <td class="text-center"><%= number_to_currency_dollar(taginfo.partner_revenue) %></td>
                  <td class="text-center"><%= taginfo.frm_date.strftime('%d-%m-%Y') %></td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td colspan="6" class="text-center">Nothing to show.</td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="row">
      <div class="col-sm-6">

        <%= link_to '<i class="fa fa-file-excel-o"></i> Export'.html_safe, export_tags_path(format: 'csv'), :class => 'btn btn-primary push-5-r push-10', :style => 'margin-top: 22px;margin-left: 20px;' %>
      </div>
      <div class="col-sm-4">
        <div class="dataTables_paginate paging_simple_numbers" id="DataTables_Table_1_paginate">
          <%= paginate @tags_infos %>
        </div>
      </div>
    </div>
  </div>
</div>