config/routes.rb
Rails.application.routes.draw do
 
  namespace :api do
    post 'users/sign_in', controller: 'users#sign_in'
    delete 'users/sign_out', controller: 'users#sign_out'
    resources :tags, only: :index
    resources :tags_infos, only: :index
  end

  resources :payments

  devise_for :users, :path_prefix => 'authentication'

  resources :users, param: :encoded_id

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get 'upload/tags_info'

  resources 'site-requests', :controller => :site_requests, :as => :site_requests

  resources :publishers, path: 'publisher/signup' do
    collection do
      get 'thank-you'
    end
  end

  resources :pages do
    post :search_index, :on => :collection
  end

  resources :tags, param: :encoded_id do
    collection do
      get ':encoded_id/export', to: 'tags#export', as: :export
    end
  end

  resources :tags_infos

  resources :uploads do
    collection { post :import }
  end

  resources :reports do
    get :download_csv, on: :collection
  end

  resources :sites do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'ads_txt/download', to: 'ads_txt#download', controller: 'ads_txt'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tags

  has_many :auth_tokens

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}

  before_validation :generate_hex, :on => :create

  before_save :downcase_fields

  attr_accessor :role

  validates :file,
            attachment_content_type: {content_type: %w(text/plain text/html), message: 'Only TEXT files are allowed.'
            },
            attachment_size: {less_than: 5.megabytes, :message => ' File must be less than 5 megabytes in size '}

  has_attached_file :file

  def generate_hex
    loop do
      self.encoded_id = SecureRandom.hex
      break unless self.class.exists?(encoded_id: encoded_id)
    end
  end

  def full_name
    "#{self.first_name.titleize} #{self.last_name.titleize}"
  end

  def self.search(search)
    if search
      where('email LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end

  def self.authenticate_user(params)
    user = User.find_by(username: params[:username])
    if user.present?
      if user.valid_password?(params[:password])
        auth_response = AuthToken.create_auth_token(user)
        data = UserSerializer.new(user)
        { status: auth_response[:status], success: auth_response[:success], message: auth_response[:message], data: data }
      else
        { status: 808, success: false, message: I18n.t('users.error.invalid_password') }
      end
    else
      { status: 404, success: false, message: I18n.t('users.error.user_not_found') }
    end
  end

  private
  def downcase_fields
    self.email.downcase!
    self.username.downcase!
  end

end

app/controllers/api/users_controller.rb
# frozen_string_literal: true

module Api
  class UsersController < ApplicationController
    include Swagger::Docs::ImpotentMethods
    before_action :authenticated_user!, only: [:sign_out]
    respond_to :json
    swagger_controller :users, 'Users'

    swagger_api :sign_in do |api|
      summary 'User Sign-in'
      param :form, 'user[username]', :string, :required, 'Username'
      param :form, 'user[password]', :string, :required, 'User Password'
      ApplicationController.add_response_params(api)
      response HTTP_STATUS_CODE_808, 'Invalid Password'
    end
    def sign_in
      required_params_present = check_required_params([:user])
      if required_params_present
        response = User.authenticate_user(params[:user])
        send_response(response[:status], response[:success], response[:message], response[:data])
      else
        send_response(HTTP_STATUS_CODE_801, false, I18n.t('params_missing.error'))
      end
    rescue => e
      send_response(HTTP_STATUS_CODE_500, false, e.message)
    end

    swagger_api :sign_out do |api|
      summary 'User Sign out'
      ApplicationController.add_auth_params(api)
      ApplicationController.add_response_params(api)
    end
    def sign_out
      token = @current_user.auth_tokens.find_by(token: request.headers['HTTP_AUTH_TOKEN'])
      if token.destroy
        send_response(HTTP_STATUS_CODE_200, true, I18n.t('users.success.user_sign_out'))
      end
    rescue => e
      send_response(HTTP_STATUS_CODE_500, false, e.message)
    end

    private

    def user_params
      params.require(:user).permit([:email, :password, :first_name, :last_name, :phone, :image, :status, :organization_id, :gender])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find_by(:encoded_id => params[:encoded_id])
  end

  def index
    @users = User.search(params[:search]).order(created_at: :desc).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    begin
      if @user.save!
        @user.add_role params[:user][:role]
        flash[:notice] = "User successfully created."
        redirect_to users_path
      else
        flash[:error] = @user.errors
        redirect_to new_user_path
      end
    rescue => err # rescues all exceptions
      logger.error(err.to_s)
      flash[:error] = err.to_s
      redirect_to new_user_path
    end
  end

  def edit
    @user = User.find(params[:encoded_id])
  end

  def update
    @user = User.find(params[:encoded_id])
    if update_user
      flash[:notice] = "User successfully updated."
      redirect_to users_path
    else
      flash[:error] = @user.errors
      redirect_to edit_user_path
    end
  end

  def destroy
    User.find(params[:encoded_id]).destroy
    flash[:success] = "User successfully deleted."
    redirect_to users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :current_password, :file)
  end

  def update_user
    @user = User.find(params[:encoded_id])
    param = params[:user][:is_active]

    if param.present?
      if param == '1'
        value = true
      else
        value = false
      end
      form_params = {:is_active => value}
    else
      form_params = user_params
    end
    return @user.update!(form_params)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="content content-narrow">
  <div class="col-md-8">
    <div class="block">
      <div class="block-content block-content-narrow">
        <%= form_for(@user, html: {:class => 'form-horizontal'}) do |f| %>
            <%= devise_error_messages! %>

            <div class="form-group">
              <label class="col-xs-7" for="example-text-input">First Name</label>

              <div class="col-sm-7">
                <%= f.text_field :first_name, autofocus: true, class: 'form-control field' %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-7" for="example-text-input">Last Name</label>

              <div class="col-sm-7">
                <%= f.text_field :last_name, autofocus: true, class: 'form-control field' %>
              </div>
            </div>


            <div class="form-group">
              <label class="col-xs-7" for="example-text-input">Email</label>

              <div class="col-sm-7">
                <%= f.email_field :email, autofocus: true, class: 'form-control field' %>
              </div>
            </div>

            <div class="form-group">
              <label class="col-xs-7" for="example-text-input">Username</label>

              <div class="col-sm-7">
                <%= f.text_field :username, autofocus: true, class: 'form-control field' %>
              </div>
            </div>

            <% if f.object.new_record? %>
                <div class="form-group">
                  <label class="col-xs-7" for="example-text-input">Password</label>

                  <div class="col-sm-7">
                    <%= f.password_field :password, autocomplete: "off", class: 'form-control field' %>
                    <% if @minimum_password_length %>
                        <div class="help-block"><%= @minimum_password_length %> characters minimum</div>
                    <% end %>
                    <div class="help-block">(Leave blank if you don't want to change it)</div>
                  </div>
                </div>

                <div class="form-group">
                  <label class="col-xs-7" for="example-text-input">Password confirmation</label>

                  <div class="col-sm-7">
                    <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control field' %>
                  </div>
                </div>
            <% end %>

            <div class="form-group">
              <label class="col-xs-7" for="example-text-input">Role</label>

              <div class="col-sm-7">
                <%= f.radio_button :role, :customer, :checked => true %>
                <%= label :role, 'Customer' %>
                <%= f.radio_button :role, :admin %>
                <%= label :role, 'Admin' %>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary ">
                  <%= f.file_field :file %>
                  <label>Upload ads.txt</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.submit f.object.new_record? ? 'Submit' : 'Update', class: 'btn btn-sm btn-primary' %>
              <%= link_to "Back", users_path, class: 'btn btn-sm btn-warning' %>
            </div>

        <% end %>
      </div>
    </div>
  </div>
</div>


<!--<h3>Cancel my account</h3>-->


<%- # <%= button_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete     -%>

app/views/users/edit.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-8">
      <h1 class="page-heading">
        User
        <small>Edit</small>
      </h1>
    </div>
    <div class="col-sm-4 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Users', users_path %></li>
        <li>Edit</li>
      </ol>
    </div>
  </div>
</div>

<%= render partial: 'users/form' %>

app/views/users/index.html.erb
<div class="content bg-gray-lighter padding-header">
  <div class="row">
    <div class="col-sm-4">
      <h1 class="page-heading ">
        Users
      </h1>
    </div>
    <div class="col-sm-4">
      <%= form_tag users_path, :method => :get, :id => "search_form" do %>
          <div class="form-material form-material-primary input-group remove-margin-t remove-margin-b">
            <%= text_field_tag(:search, params[:search], :class => "form-control", :id => "users", :placeholder => "Search", :onkeyup => "clear_search()") %>
            <span class="input-group-addon"><i class="si si-magnifier" , onClick="submit_search()"></i></span>
          </div>
      <% end %>
    </div>
    <div class="col-sm-4 text-right">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Add User', new_user_path %></li>
      </ol>
    </div>
  </div>
</div>

<div class="content">
  <div class="block">
    <div class="table-responsive">
      <table class="table table-borderless table-header-bg text-center remove-margin-b">
        <thead>
        <tr>
          <th class="text-center">Name</th>
          <th class="text-center">Username</th>
          <th class="text-center">Email ID</th>
          <th class="text-center">Role</th>
          <th class="text-center">Active</th>
          <th class="text-center">Actions</th>
          <th class="text-center">Ads.Txt</th>
        </tr>
        </thead>
        <tbody>
        <% if @users.present? %>
            <% @users.each do |user| %>
                <tr>
                  <td class="text-center"><%= user.full_name %></td>
                  <td class="text-center"><%= user.username %></td>
                  <td class="text-center"><%= user.email %></td>
                  <td class="text-center"><%= user.roles.present? ? user.roles.first.name : 'No role' %></td>

                  <td class="text-center">
                    <%= form_for(user, :method => 'put', url: user_path(:encoded_id => user.id)) do |f| %>
                        <label class="css-input switch switch-sm switch-primary">
                          <% if user.is_active %>
                              <%= f.check_box :is_active, {checked: true, :class => 'is-active'} %>
                          <% else %>
                              <%= f.check_box :is_active, {:class => 'is-active'} %>
                          <% end %>
                          <span></span>
                        </label>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <%= link_to 'Edit', edit_user_path(user) %>
                    <%= link_to 'Delete', user_path(user), method: :delete, data: {confirm: 'Are you sure?'} %>
                  </td>
                  <td class="text-center">
                    <% if user.file_file_name.present? %>
                        <% if user.file_file_name.include? ".txt" %>
                            <%= link_to image_tag('icon_txt.png', alt: 'Download TXT'), user.file.url, :title => 'Download TXT' %>
                        <% else %>
                            <%= link_to image_tag('icon_all_extensions.png', alt: 'Download'), user.file.url, :title => 'Download' %>
                        <% end %>
                    <% else %>
                        <%= image_tag('upload_tag.png', alt: 'Upload ads.txt', :title => 'Upload ads.txt') %>
                    <% end %>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td colspan="6" class="text-center">Nothing to show.</td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="dataTables_paginate paging_simple_numbers">
      <%= paginate @users %>
    </div>
  </div>
</div>
<script>
    $('.is-active').on("change", function () {
        $(this).closest("form").submit();
    });
</script>

app/views/users/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-8">
      <h1 class="page-heading">
        User
        <small>Add</small>
      </h1>
    </div>
    <div class="col-sm-4 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Users', users_path %></li>
        <li>Add</li>
      </ol>
    </div>
  </div>
</div>

<%= render partial: 'users/form' %>

app/views/users/show.html.erb
<h1><%= @user.email%></h1>