config/routes.rb
Rails.application.routes.draw do
 
  namespace :api do
    post 'users/sign_in', controller: 'users#sign_in'
    delete 'users/sign_out', controller: 'users#sign_out'
    resources :tags, only: :index
    resources :tags_infos, only: :index
  end

  resources :payments

  devise_for :users, :path_prefix => 'authentication'

  resources :users, param: :encoded_id

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get 'upload/tags_info'

  resources 'site-requests', :controller => :site_requests, :as => :site_requests

  resources :publishers, path: 'publisher/signup' do
    collection do
      get 'thank-you'
    end
  end

  resources :pages do
    post :search_index, :on => :collection
  end

  resources :tags, param: :encoded_id do
    collection do
      get ':encoded_id/export', to: 'tags#export', as: :export
    end
  end

  resources :tags_infos

  resources :uploads do
    collection { post :import }
  end

  resources :reports do
    get :download_csv, on: :collection
  end

  resources :sites do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'ads_txt/download', to: 'ads_txt#download', controller: 'ads_txt'

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :user

  enum mode: ['PayPal', 'eCheck', 'Wire Transfer']

  enum status: ['Paid', 'Pending']


  def self.search(search)
    if search
      where('email LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index

    @payments = {}

    if current_user.has_role? :admin

      add_breadcrumb 'Add Payments', :new_payment_path
      add_breadcrumb 'All Payments'

      @payments = Payment.includes(:user).search(params[:search]).page(params[:page]).per(30)

    else

      add_breadcrumb 'Summary', :root_path
      add_breadcrumb 'All Payments'

      @payments = Payment.joins(:user).where(:user_id => current_user.id).page(params[:page]).per(12)

      counts = Hash.new 0

      @payments.each do |payment|

        date = payment.payment_date.to_date

        amount = payment.payment_amount

        counts[payment.status] += 1

      end

      @count_status = counts

    end

  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
    @payment = Payment.find(params[:id])
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params.merge(created_by: current_user.id))
    respond_to do |format|
      if @payment.save
        format.html { redirect_to payments_path, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params.merge(updated_by: current_user.id))
        format.html { redirect_to payments_path, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { redirect_to edit_payment_path, alert: @payment.errors }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_payment
    @payment = Payment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def payment_params
    params.require(:payment).permit(:payment_id, :user_id, :payment_date, :payment_amount, :mode, :status, :created_by, :updated_by)
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<div class="content content-narrow">
  <div class="col-md-8">
    <div class="block">
      <div class="block-content block-content-narrow">
        <%= form_for(@payment, html: {:class => 'js-validation-material form-horizontal margin-top-40 tags-info-form'}) do |f| %>

            <% if @payment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

                  <ul>
                    <% @payment.errors.full_messages.each do |message| %>
                        <li><%= message %></li>
                    <% end %>
                  </ul>
                </div>
            <% end %>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary ">
                  <%= f.collection_select(:user_id, User.with_role(:customer).where(:is_active => true).order(:email), :id, :email, {:prompt => true}, {:class => 'form-control jsSelect'}) %>
                  <label>Email Id</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary ">
                  <%= f.text_field :payment_date, :class => 'js-datepicker form-control', id: 'payment_date', 'data-date-format' => "dd MM, yyyy" %>
                  <label>Date</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary ">
                  <%= f.text_field :payment_amount, autofocus: true, class: 'form-control field' %>
                  <label>Amount</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary ">
                  <%= f.select(:mode, Payment.modes.keys.map {|mode| [mode.titleize,mode]}, {}, { :class => 'form-control jsSelect' }) %>
                  <label>Payment Method</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <div class="col-xs-9">
                <div class="form-material form-material-primary">
                  <%= f.select(:status, Payment.statuses.keys.map {|status| [status.titleize,status]}, {}, { :class => 'form-control jsSelect' }) %>
                  <label>Payment Status</label>
                </div>
              </div>
            </div>

            <div class="form-group">
              <%= f.submit f.object.new_record? ? 'Submit' : 'Update', class: 'btn btn-sm btn-primary tags-info-btn' %>
              <%= link_to "Back", payments_path, class: 'btn btn-sm btn-warning' %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    $(document).ready(function () {
        $(function () {
            App.initHelpers(['datepicker']);
        });
    });
</script>

app/views/payments/edit.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-8">
      <h1 class="page-heading">
        Editing Payments
        <small>Edit</small>
      </h1>
    </div>
  </div>
</div>

<%= render partial: 'payments/form' %>

app/views/payments/index.html.erb
<% if current_user.has_role? :admin %>
    <%= render partial: 'payments/index/admin' %>
<% else %>
    <%= render partial: 'payments/index/customer' %>
<% end %>

app/views/payments/new.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-8">
      <h1 class="page-heading">
        Payments
        <small>Add</small>
      </h1>
    </div>
    <div class="col-sm-4 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Show Payments', payments_path %></li>
        <li>Add</li>
      </ol>
    </div>
  </div>
</div>

<%= render 'form' %>

app/views/payments/show.html.erb
<div class="content bg-gray-lighter">
  <div class="row items-push">
    <div class="col-sm-4">
      <h1 class="page-heading">
        Payments Processed
      </h1>
    </div>

    <div class="col-sm-4 text-right hidden-xs">
      <ol class="breadcrumb push-10-t">
        <li><%= link_to 'Add Payment', new_payment_path %></li>
        <li>Show Payments</li>
      </ol>
    </div>
  </div>
</div>

<div class="content">
  <div class="block">
    <div class="block-content">
      <table class="table table-responsive table-header-bg">
        <thead>
        <tr>
          <th class="text-center">#</th>
          <th class="text-center">Name</th>
          <th class="text-center">Date</th>
          <th class="text-center">Amount</th>
          <th class="text-center">Method</th>
          <th class="text-center">Status</th>
        </tr>
        </thead>
        <tbody>
        <% if @tags.present? %>
            <% @tags.each_with_index do |tag, i| %>
                <tr>
                  <td class="text-center"><%= (i+1) %></td>
                  <td class="text-center"><%= tag.name %></td>
                  <td class="text-center"><%= tag.created_at.strftime('%d-%m-%Y') %></td>
                  <td class="text-center">
                    <%= form_for(tag, :method => 'put', url: tag_path(:encoded_id => tag.id)) do |f| %>
                        <label class="css-input switch switch-sm switch-primary">
                          <% if tag.is_active %>
                              <%= f.check_box :is_active, {checked: true, :class => 'is-active'} %>
                          <% else %>
                              <%= f.check_box :is_active, { :class => 'is-active'} %>
                          <% end %>

                          <span></span>
                        </label>
                    <% end %>
                  </td>
                  <td class="text-center">
                    <%= link_to '<i class="fa fa-database"></i> View Data'.html_safe, tag_path(tag.encoded_id), :class => 'btn btn-info push-5-r push-10' %>
                  </td>
                  <td class="text-center">
                    <% if tag.is_active %>
                        <%= link_to 'Edit', edit_tag_path(tag.encoded_id)  %> &nbsp;
                        <%= link_to 'Delete', tag_path(tag.encoded_id), method: :delete, data: {confirm: 'Are you sure?'} %>
                    <% else %>
                        Edit Delete
                    <% end%>
                  </td>
                  <td class="text-center">
                    <% if tag.file_file_name.present? %>
                        <%= link_to 'Download Tags', tag.file.url  %>
                    <% else %>
                        Upload Tag
                    <% end%>
                  </td>
                </tr>
            <% end %>
        <% else %>
            <tr>
              <td colspan="6" class="text-center">Nothing to show.</td>
            </tr>
        <% end %>
        </tbody>
      </table>
    </div>



  </div>
</div>

<script>
    $('.is-active').on("change", function(){
        $(this).closest("form").submit();
    });
</script>