config/routes.rb
Rails.application.routes.draw do
 
  namespace :api do
    post 'users/sign_in', controller: 'users#sign_in'
    delete 'users/sign_out', controller: 'users#sign_out'
    resources :tags, only: :index
    resources :tags_infos, only: :index
  end

  resources :payments

  devise_for :users, :path_prefix => 'authentication'

  resources :users, param: :encoded_id

  devise_scope :user do
    root to: 'devise/sessions#new'
  end

  get 'upload/tags_info'

  resources 'site-requests', :controller => :site_requests, :as => :site_requests

  resources :publishers, path: 'publisher/signup' do
    collection do
      get 'thank-you'
    end
  end

  resources :pages do
    post :search_index, :on => :collection
  end

  resources :tags, param: :encoded_id do
    collection do
      get ':encoded_id/export', to: 'tags#export', as: :export
    end
  end

  resources :tags_infos

  resources :uploads do
    collection { post :import }
  end

  resources :reports do
    get :download_csv, on: :collection
  end

  resources :sites do
    get :autocomplete_tag_name, :on => :collection
  end

  get 'ads_txt/download', to: 'ads_txt#download', controller: 'ads_txt'

end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tags

  has_many :auth_tokens

  validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}

  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, presence: true, length: {maximum: 105}, uniqueness: {case_sensitive: false}, format: {with: VALID_EMAIL_REGEX}

  before_validation :generate_hex, :on => :create

  before_save :downcase_fields

  attr_accessor :role

  validates :file,
            attachment_content_type: {content_type: %w(text/plain text/html), message: 'Only TEXT files are allowed.'
            },
            attachment_size: {less_than: 5.megabytes, :message => ' File must be less than 5 megabytes in size '}

  has_attached_file :file

  def generate_hex
    loop do
      self.encoded_id = SecureRandom.hex
      break unless self.class.exists?(encoded_id: encoded_id)
    end
  end

  def full_name
    "#{self.first_name.titleize} #{self.last_name.titleize}"
  end

  def self.search(search)
    if search
      where('email LIKE ?', "%#{search.downcase}%")
    else
      all
    end
  end

  def self.authenticate_user(params)
    user = User.find_by(username: params[:username])
    if user.present?
      if user.valid_password?(params[:password])
        auth_response = AuthToken.create_auth_token(user)
        data = UserSerializer.new(user)
        { status: auth_response[:status], success: auth_response[:success], message: auth_response[:message], data: data }
      else
        { status: 808, success: false, message: I18n.t('users.error.invalid_password') }
      end
    else
      { status: 404, success: false, message: I18n.t('users.error.user_not_found') }
    end
  end

  private
  def downcase_fields
    self.email.downcase!
    self.username.downcase!
  end

end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ReportsHelper
  before_action :authenticate_user!
  respond_to :html, :js

  def index
    add_breadcrumb 'home', :root_path
    add_breadcrumb 'Websites', :tags_path
    add_breadcrumb 'Reports'

    @summary = {}
    @tags_infos = {}

    if params[:tag_id].present?

      @tag = Tag.find_by(id: params[:tag_id][:id])

      if @tag.present?
        @tags_infos = TagsInfo.includes(:tag).where(tag_id: params[:tag_id][:id]).where('DATE(frm_date) >= ? AND to_date <= ?', Date.strptime(params[:start_date], '%m/%d/%Y'), Date.strptime(params[:end_date], '%m/%d/%Y')).order(tag_id: :desc, frm_date: :asc).page(params[:page]).per(30)

        @summary = fetch_data(@tags_infos)
        flash.clear
      else
        flash[:error] = 'Invalid tag'
      end
    end

    respond_to do |format|
      format.html
      format.js
    end

  rescue => e
    flash[:error] = 'Something went wrong. Please drop us an email.'

    respond_to do |format|
      format.html
      format.js
    end
  end

  def download_csv
    tags_ids = params[:tag_ids].split(',')
    if tags_ids.present?
        @tags_infos = TagsInfo.includes(:tag).where(tag_id: tags_ids)
                          .where('DATE(frm_date) >= ? AND to_date <= ?',
                                 Date.strptime(params[:start_date], '%m/%d/%Y'),
                                 Date.strptime(params[:end_date], '%m/%d/%Y'))
                          .order(tag_id: :desc, frm_date: :asc)

        @summary = fetch_data(@tags_infos)

        send_data write_to_csv(@tags_infos, @summary), :type => "text/csv", :filename => "#{Date.today}_report.csv"
    end
  end

  protected

  def fetch_data(tags_infos)
    summary = {}
    total_ad_request = 0
    total_match_request = 0
    total_partner_revenue = 0
    avg_ecpm = []
    avg_fill_rate = []

    tags_infos.each do |x|
      total_ad_request = total_ad_request + x.ad_request.round(1)
      total_match_request = total_match_request + x.match_request.round(1)
      total_partner_revenue = total_partner_revenue + x.partner_revenue.round(1)
      avg_ecpm << x.ecpm
      avg_summary_ecpm = avg_ecpm.inject(0.0) { |sum, x| sum + x } / avg_ecpm.size
      avg_fill_rate << x.fill_rate
      avg_summary_fill_rate = avg_fill_rate.inject(0.0) { |sum, x| sum + x } / avg_fill_rate.size

      summary = { :total_ad_request => total_ad_request, :total_match_request => total_match_request,
                  :total_partner_revenue => total_partner_revenue, :total_ecpm => avg_summary_ecpm, :total_fill_rate => avg_summary_fill_rate }
    end
    summary
  end

end

app/helpers/reports_helper.rb
module ReportsHelper

  def date_range_options
    date_range_options = [
        ['Custom Date Range', 'custom'],
        ['Today', 'today'],
        ['Yesterday', 'yesterday'],
        ['This Week(Sun-today)', 'this_week'],
        ['Past 7 days', 'past_7_days'],
        ['This Month(1st-today)', 'this_month'],
        ['Past 30 days', 'past_30_days'],
        ['Past Month', 'past_month'],
        ['Past 90 days', 'past_90_days'],
        ['This Year(Jan 1-today)', 'this_year'],
        ['Past 365 days', 'past_365_days']
    ]
    return date_range_options
  end

  def write_to_csv(tags_infos, summary)
    attributes = ['NAME', 'DATE',	'TOTAL IMPRESSIONS',	'PAID IMPRESSIONS',	'ECPM',	'FILL RATE',	'PARTNER REVENUE']
    CSV.generate(headers: true) do |csv|
      csv << attributes

      tags_infos.each do |tag_info|
        csv << [tag_info.tag.name,
                tag_info.frm_date,
                tag_info.ad_request.to_i,
                tag_info.match_request.to_i,
                tag_info.ecpm.present? ? "$ #{tag_info.ecpm.round(2)}" : '',
                tag_info.fill_rate.present? ? "#{tag_info.fill_rate} %" : '',
                tag_info.partner_revenue.present? ? "$ #{tag_info.partner_revenue.round(2)}" : '']
      end

      csv << ['', 'Total',
              summary[:total_ad_request],
              summary[:total_match_request],
              summary[:total_ecpm].present? ? "$ #{summary[:total_ecpm].round(2)}" : '',
              summary[:total_fill_rate].present? ? "#{summary[:total_fill_rate]} %" : '',
              summary[:total_partner_revenue].present? ? "$ #{summary[:total_partner_revenue].round(2)}" : ''
      ]
    end
  end
end

app/views/reports/_tag_info.html.erb
<table class='table table-borderless table-header-bg text-center remove-margin-b'>
  <thead>
  <tr>
    <th class='text-center'>Name</th>
    <th class='text-center'>Date</th>
    <th class='text-center'>Total Impressions</th>
    <th class='text-center'>Paid Impressions</th>
    <th class='text-center'>eCPM</th>
    <th class='text-center'>Fill Rate</th>
    <th class='text-center'>Partner Revenue</th>
  </tr>
  </thead>
  <tbody>
  <% if @tags_infos.present? %>
      <% @tags_infos.each do |tag_info| %>
          <tr>
            <td class='text-center'><%= tag_info.tag.name %></td>
            <td class='text-center'><%= tag_info.frm_date %></td>
            <td class='text-center'><%= number_with_delimiter(tag_info.ad_request.to_i, delimiter: ',') %></td>
            <td class='text-center'><%= number_with_delimiter(tag_info.match_request.to_i, delimiter: ',') %></td>
            <td class='text-center'><%= number_to_currency_dollar(tag_info.ecpm) %></td>
            <td class='text-center'><%= number_to_percentage_fill(tag_info.fill_rate) %></td>
            <td class='text-center'><%= number_to_currency_dollar(tag_info.partner_revenue) %></td>
          </tr>
      <% end %>
      <tr>
        <td class='text-center' colspan="2"><h3 class='block-title'>Total</h3></td>
        <td class='text-center'>
          <h3 class='block-title'><%= number_with_delimiter(@summary[:total_ad_request].to_i, delimiter: ',') %></h3>
        </td>
        <td class='text-center'>
          <h3 class='block-title'><%= number_with_delimiter(@summary[:total_match_request].to_i, delimiter: ',') %></h3>
        </td>
        <td class='text-center'>
          <h3 class='block-title'><%= number_to_currency_dollar(@summary[:total_ecpm]) %></h3></td>
        <td class='text-center'>
          <h3 class='block-title'><%= number_to_percentage_fill(@summary[:total_fill_rate]) %></h3></td>
        <td class='text-center'>
          <h3 class='block-title'><%= number_to_currency_dollar(@summary[:total_partner_revenue]) %></td>
      </tr>
  <% else %>
      <tr>
        <td colspan='6' class='text-center'>Nothing to show.</td>
      </tr>
  <% end %>
  </tbody>
</table>

<% if @tags_infos.present? %>
    <div id="page_links">
      <%= paginate @tags_infos, :remote => true %>
    </div>
<% end %>

app/views/reports/index.html.erb
<div class='content bg-gray-lighter'>
  <div class='row items-push'>
    <div class='col-sm-7'>
      <h2>Daily Stats Report</h2>
      <small>Gives you daily information on the revenue brought in by ad tags.</small>
    </div>
    <div class='col-sm-5 text-right hidden-xs'>
      <ol class='breadcrumb push-10-t'>
        <%= render_breadcrumbs :tag => :li, :separator => '' %>
      </ol>
    </div>
  </div>
</div>

<div class="reports_flash">
</div>

<div class="content bg-white border-b padding-24">
  <div class="row items-push text-uppercase">
    <%= form_tag reports_path, :method => :get, remote: true, :class => 'form-search' do %>
        <div class="col-xs-6 col-sm-3">
          <div class="font-w700 text-gray-darker animated fadeIn">Date Range</div>
      <span class="h2 font-w300 text-primary animated flipInX">
        <%= select_tag :date_range, options_for_select(date_range_options, selected: 'yesterday'), :class => "form-control width-80" %>
      </span>
        </div>

        <div class="col-xs-6 col-sm-3">
          <div class="font-w700 text-gray-darker animated fadeIn">Custom Date Range</div>
          <div class="text-muted animated fadeIn">
            <%= text_field_tag :start_date, Date.yesterday.strftime('%m/%d/%Y'), :class => ' form-control margin-bottom-10', id: 'report_start_date', :required => true %>
            <%= text_field_tag :end_date, Date.yesterday.strftime('%m/%d/%Y'), :class => 'form-control', id: 'report_end_date', :required => true %>
          </div>
        </div>
        <% role = current_user.roles.present? ? current_user.roles.first.name : '' %>
        <% if role == 'admin' %>
            <div class="col-xs-6 col-sm-3">
              <div class="font-w700 text-gray-darker animated fadeIn">Filter By</div>
              <div class="text-muted animated fadeIn">
                <%= collection_select :tag_id, :id, Tag.all, :id, :name, {:include_blank => false}, {:class => 'form-control ', :multiple => true} %>
              </div>
            </div>
        <% else %>
            <div class="col-xs-6 col-sm-3">
              <div class="font-w700 text-gray-darker animated fadeIn">Filter By</div>
              <div class="text-muted animated fadeIn">
                <%= collection_select :tag_id, :id, Tag.where(user_id: current_user.id), :id, :name, {:include_blank => false}, {:class => 'form-control ', :multiple => true} %>
              </div>
            </div>
        <% end %>

       <div class="col-xs-6 col-sm-3">
          <div class="text-muted animated fadeIn margin-top-20">
            <%= submit_tag 'Generate Report', class: "btn btn-primary" %>
          </div>
        </div>
  <% end %>

    <%= form_tag download_csv_reports_path, :method => :get, :class => 'form-search' do %>
        <div class="col-xs-6 col-sm-3">
          <%= hidden_field_tag 'tag_ids', '' %>
          <%= hidden_field_tag 'start_date', '' %>
          <%= hidden_field_tag 'end_date', '' %>

          <div class="text-muted animated fadeIn margin-top-20">
            <%= submit_tag 'Download CSV', class: "btn btn-info download_csv", disabled: 'disabled'%>
          </div>
        </div>
    <% end %>
  </div>
</div>

<!-- Page Content -->
<div class='content'>
  <div class='block'>
    <div class="table-responsive">
      <div class="reports_index">
        <table class='table table-borderless table-header-bg text-center remove-margin-b'>
          <thead>
          <tr>
            <th class='text-center'>Name</th>
            <th class='text-center'>Date</th>
            <th class='text-center'>Total Impressions</th>
            <th class='text-center'>Paid Impressions</th>
            <th class='text-center'>eCPM</th>
            <th class='text-center'>Fill Rate</th>
            <th class='text-center'>Partner Revenue</th>
          </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/reports/index.js.erb
<% if flash.present? %>
$('.reports_flash').html("<%= escape_javascript (render partial: 'static/notice_banner' ) %>");
<% else %>
$('.reports_flash').html(" ");
<% end %>

$('.reports_index').html("<%= escape_javascript (render partial: 'tag_info', locals: { tag_infos: @tag_infos } ) %>");